name: Reject PRs to Non-Main Branches

on:
  pull_request:
    branches-ignore:
      - main

jobs:
  close-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Close the PR
        run: |
          echo "Closing pull request to disallowed branch..."
          gh pr close "$PR_URL" --comment "❌ Only pull requests to 'main' are allowed."
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}