#name: Auto-Close PRs to Production from Non-Main
#
#on:
#  pull_request:
#    branches:
#      - production  # Only run when PRs target production
#
#jobs:
#  validate-source:
#    runs-on: ubuntu-latest
#    permissions:
#      pull-requests: write  # Allow closing PRs
#      contents: read        # Required for repo access
#
#    steps:
#      - name: Check source branch
#        id: check-branch
#        run: |
#          SOURCE_BRANCH="${{ github.event.pull_request.head.ref }}"
#          echo "Source branch is: $SOURCE_BRANCH"
#          if [ "$SOURCE_BRANCH" != "main" ]; then
#            echo "CLOSE_PR=true" >> $GITHUB_ENV
#          else
#            echo "CLOSE_PR=false" >> $GITHUB_ENV
#          fi
#
#      - name: Close PR if not from main
#        if: env.CLOSE_PR == 'true'
#        run: |
#          echo "Rejecting PR to production from non-main branch..."
#          gh pr close "$PR_URL" --comment "❌ Pull requests to 'production' are only allowed from the 'main' branch."
#        env:
#          PR_URL: ${{ github.event.pull_request.html_url }}
#          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}